#!/bin/sh
# Copyright (C) Sierra Wireless Inc. Use of this work is subject to license.
#
# MediaTek wireless 7697 specific applications start or stop here
# MediaTek WIFI IoT board is managed by SPI bus.

#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mnt/flash/wifi

mt_wifi_start() {
    lsmod | grep 2_mt7697wifi_core >/dev/null                                            
    if [ $? -eq 1 ]; then                         
        insmod /legato/systems/current/modules/2-mt7697wifi_core.ko itf_idx_start=$1 || exit 127
        echo "Initialized MT7697 80211 core";                                       
        sleep 2
    fi
                                                                     
    ifconfig -a | grep wlan$1 >/dev/null                                         
    if [ $? -ne 0 ] ; then                                                      
        echo "Failed to init MT7697 80211 core"; 
	exit 127                            
    fi 
                                                                         
    ifconfig wlan$1 up >/dev/null                                                
    if [ $? -ne 0 ] ; then                                                      
        echo "Failed to start MT7697 80211 core"; 
	exit 127                            
    fi                                                                         
} 

mt_wifi_stop() { 
    kill -9 $(pidof wpa_supplicant)
                                                               
    ifconfig | grep wlan$1 >/dev/null                                            
    if [ $? -eq 0 ]; then                                                       
       ifconfig wlan$1 down                                                      
    fi

    lsmod | grep 2_mt7697wifi_core >/dev/null                                         
    if [ $? -eq 0 ]; then
        rmmod 2_mt7697wifi_core || exit 127
        echo "Removed MT7697 80211 core"; exit 127         
    fi                                                             
}                                                                               
                                                                                
case "$1" in                                                                    
    start)                                                                      
        mt_wifi_start $2                                                          
        ;;                                                                      
    stop)                                                                       
        mt_wifi_stop $2                                                           
        ;;                                                                      
    restart)                                                                    
        mt_wifi_stop $2                                                          
        mt_wifi_start $2                                                         
        ;;                                                                      
    *)                                                                          
        exit 1                                                                  
        ;;        

esac                                                                            
                                                                                
exit 0                                                               
