#!/bin/sh
# Copyright (C) Sierra Wireless Inc. Use of this work is subject to license.
#
# MediaTek wireless 7697 specific applications start or stop here
# MediaTek WIFI IoT board is managed by SPI bus.

#export PATH=$PATH:/usr/bin:/bin:/usr/sbin:/sbin
#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/tmp

mt_wifi_start() {
#    insmod /tmp/spisvc.ko || exit 127
    lsmod | grep spi-cp2130 >/dev/null                                            
    if [ $? -eq 1 ]; then
        insmod /tmp/spi-cp2130.ko || exit 127
        for f in `ls -d /sys/class/gpio/gpiochip*`; do echo $f `cat $f/label $f/base $f/ngpio` ; done
        echo -n 0,2,6,0,0,1,2,0,0,0,0,mt7697 > /sys/devices/platform/msm_hsic_host/usb1/1-1/1-1.1/1-1.1:1.0/channel_config                                                                     
    fi

    lsmod | grep cfg80211 >/dev/null                                            
    if [ $? -eq 1 ]; then
        insmod /tmp/cfg80211.ko || exit 127
    fi

    lsmod | grep mac80211 >/dev/null                                            
    if [ $? -eq 1 ]; then
        insmod /tmp/mac80211.ko || exit 127
    fi                                                                 

    lsmod | grep mt7697q >/dev/null                                            
    if [ $? -eq 1 ]; then
        insmod /tmp/mt7697q.ko || exit 127
        echo "Initialized MT7697 queues"; 
    fi
               
    lsmod | grep mt7697wifi_core >/dev/null                                            
    if [ $? -eq 1 ]; then                         
        insmod /tmp/mt7697wifi_core.ko || exit 127
        echo "Initialized MT7697 80211 core";                                       
        sleep 2
    fi
                                                                     
    ifconfig -a | grep wlan0 >/dev/null                                         
    if [ $? -ne 0 ] ; then                                                      
        echo "Failed to init MT7697 80211 core"; 
	exit 127                            
    fi                                                                          
    ifconfig wlan0 up >/dev/null                                                
    if [ $? -ne 0 ] ; then                                                      
        echo "Failed to start MT7697 80211 core"; 
	exit 127                            
    fi

    /tmp/wpa_supplicant -i wlan0 -D wext -c /etc/swi-mobile -B                                                                          
} 

mt_wifi_stop() {                                                                
    ifconfig | grep wlan0 >/dev/null                                            
    if [ $? -eq 0 ]; then                                                       
       ifconfig wlan0 down                                                      
    fi
    lsmod | grep mt7697wifi_core >/dev/null                                         
    if [ $? -eq 0 ]; then
        rmmod mt7697wifi_core || exit 127
        echo "Removed MT7697 80211 core"; exit 127         
    fi                                                                          
}                                                                               
                                                                                
case "$1" in                                                                    
    start)                                                                      
        mt_wifi_start                                                           
        ;;                                                                      
    stop)                                                                       
        mt_wifi_stop                                                            
        ;;                                                                      
    restart)                                                                    
        mt_wifi_stop                                                            
        mt_wifi_start                                                           
        ;;                                                                      
    *)                                                                          
        exit 1                                                                  
        ;;        

esac                                                                            
                                                                                
exit 0                                                               
