#ifndef COMPAT_AUTOCONF_INCLUDED
#define COMPAT_AUTOCONF_INCLUDED
/*
 * Automatically generated file, don't edit!
 * Changes will be overwritten
 */

#define CPTCFG_WIRELESS 1
#define CPTCFG_NET_CORE 1
#define CPTCFG_EXPERT 1
#define CPTCFG_BP_MODULES 1
#define CPTCFG_BPAUTO_REFCOUNT 1
#define CPTCFG_CFG80211_MODULE 1
#define CPTCFG_CFG80211_DEFAULT_PS 1
#define CPTCFG_CFG80211_CRDA_SUPPORT 1
#define CPTCFG_CFG80211_WEXT 1
#define CPTCFG_WLAN 1
#define CPTCFG_WLAN_VENDOR_BROADCOM 1
#define CPTCFG_BRCMUTIL_MODULE 1
#define CPTCFG_BRCMFMAC_MODULE 1
#define CPTCFG_BRCMFMAC_PROTO_BCDC 1
#define CPTCFG_BRCMFMAC_SDIO 1
#define CPTCFG_BRCMFMAC_USB 1
#define CPTCFG_BACKPORTED_WIRELESS 1
#define CPTCFG_BACKPORTED_NET_CORE 1
#define CPTCFG_BACKPORTED_EXPERT 1
#define CPTCFG_BACKPORTED_BP_MODULES 1
#define CPTCFG_BACKPORTED_BPAUTO_REFCOUNT 1
#define CPTCFG_BACKPORTED_CFG80211_MODULE 1
#define CPTCFG_BACKPORTED_CFG80211_DEFAULT_PS 1
#define CPTCFG_BACKPORTED_CFG80211_CRDA_SUPPORT 1
#define CPTCFG_BACKPORTED_CFG80211_WEXT 1
#define CPTCFG_BACKPORTED_WLAN 1
#define CPTCFG_BACKPORTED_WLAN_VENDOR_BROADCOM 1
#define CPTCFG_BACKPORTED_BRCMUTIL_MODULE 1
#define CPTCFG_BACKPORTED_BRCMFMAC_MODULE 1
#define CPTCFG_BACKPORTED_BRCMFMAC_PROTO_BCDC 1
#define CPTCFG_BACKPORTED_BRCMFMAC_SDIO 1
#define CPTCFG_BACKPORTED_BRCMFMAC_USB 1
#endif /* COMPAT_AUTOCONF_INCLUDED */
